/**
 * Renders the apply-run skill's "standing default answers" from the candidate
 * profile, into a gitignored file the skill reads.
 *
 * Run:  npm run db:generate-apply-defaults
 *
 * Why this exists: these answers used to be hand-written prose inside
 * `.claude/skills/apply-run/SKILL.md`, which is a TRACKED file. Every fork
 * therefore inherited the original candidate's name, email, GitHub URL, visa
 * status, demographics and resume filename — and a forker who skipped the
 * manual rewrite would submit real applications answering as him. The fix isn't
 * a better checklist item, it's removing the shared mutable prose: the skill
 * now ships only genuinely shared knowledge (ATS behaviour), and the personal
 * half is generated per-instance and never committed.
 *
 * Unset fields render as an explicit "NOT SET — ask the candidate" line rather
 * than falling back to a default. A wrong answer here is submitted to a real
 * employer under someone's name, so silence is safer than a guess.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { db } from "@/lib/db/client";
import { candidateProfile } from "@/lib/db/schema";

const OUT = path.join(process.cwd(), ".claude/skills/apply-run/standing-answers.md");

const [profile] = await db.select().from(candidateProfile).limit(1);
if (!profile) {
  console.error("No candidate profile seeded yet. Run `npm run db:seed-profile` first.");
  process.exit(1);
}

const d = profile.applyDefaults ?? {};
const missing: string[] = [];

/** Renders a value, or records it as unset so the skill asks instead of guessing. */
function val(label: string, v: string | undefined | null, hint: string): string {
  if (v && String(v).trim()) return `**${v}**`;
  missing.push(`${label} — ${hint}`);
  return "**NOT SET — ask the candidate, do not guess**";
}

const resumeFilename = `${profile.name.trim().replace(/\s+/g, "_")}_Resume.pdf`;

const demographics = [
  profile.genderIdentity && `Gender ${profile.genderIdentity}`,
  profile.raceEthnicity && `Race/ethnicity ${profile.raceEthnicity}`,
  profile.sexualOrientation && `Sexual orientation ${profile.sexualOrientation}`,
  profile.veteranStatus && `Veteran status ${profile.veteranStatus}`,
  profile.disabilityStatus && `Disability status ${profile.disabilityStatus}`,
].filter(Boolean);

const educationList = (profile.education ?? [])
  .map((e) => `${e.degree}${e.school ? ` (${e.school})` : ""}`)
  .join("; ");

const lines: (string | null)[] = [
  "<!-- GENERATED by `npm run db:generate-apply-defaults` from the candidate profile.",
  "     Do not hand-edit: re-running overwrites this file. Change the profile instead",
  "     (local/profile.seed.json -> `npm run db:seed-profile`), then regenerate.",
  "     This file is gitignored on purpose — it is personal data. -->",
  "",
  "# Standing default answers (don't re-ask these)",
  "",
  `Generated for **${profile.name}** <${profile.email}>. Treat these as resolved facts, not per-application judgement calls.`,
  "",
  "## Identity",
  "",
  `- Name: **${profile.name}**`,
  `- Email: **${profile.email}**`,
  `- Phone: ${val("phone", profile.phone, "set `phone` on the profile")}`,
  `- LinkedIn: ${val("linkedin", profile.linkedin, "set `linkedin` on the profile")}`,
  `- GitHub URL (if asked): ${val("githubUrl", d.githubUrl, "set `applyDefaults.githubUrl`")}`,
  `- Location: ${val("location", profile.location, "set `location` on the profile")}${profile.zipCode ? ` (zip ${profile.zipCode})` : ""}`,
  `- Current/most recent employer: ${val("currentCompany", profile.currentCompany, "set `currentCompany`")}`,
  "",
  `- **Resume filename shown to the ATS must always be \`${resumeFilename}\`** — never the job-specific storage slug (e.g. \`airops-founding-biz-ops-lead-ec599901.pdf\`), which reads as obviously auto-generated. The app's internal slug (the Supabase key and the \`/api/resumes/{slug}\` route) stays as-is; this only affects the *local* filename handed to Playwright's \`setInputFiles\`, since that is what the browser reports. When downloading a tailored resume into \`.playwright-mcp/\`, save it as \`${resumeFilename}\` and upload that. Delete it after closing out the job.`,
  "",
  "## Work authorization and eligibility",
  "",
  `- Authorized to work without sponsorship: **${profile.workAuthorized ? "Yes" : "NO — verify with the candidate before answering any work-auth question"}**${profile.requiresSponsorship ? " (note: `requiresSponsorship` is true on the profile — reconcile these before relying on this answer)" : ""}`,
  `- Visa status (free text): ${val("visaStatus", d.visaStatus, "set `applyDefaults.visaStatus`, e.g. \"U.S. Citizen\"")}`,
  `- Security clearance eligibility: ${d.securityClearanceEligible === undefined ? val("securityClearanceEligible", undefined, "set `applyDefaults.securityClearanceEligible`") : `**${d.securityClearanceEligible ? "Yes, eligible to obtain/maintain one" : "No"}**`}`,
  "",
  "## Recurring form questions",
  "",
  `- "How did you hear about us": ${val("howHeardDefault", profile.howHeardDefault, "set `howHeardDefault` on the profile")}, always.`,
  `- Relocation / onsite / commute: **${profile.requiresRelocationAssistance === false ? "Yes" : "Yes"}**. If offered a choice of office, prefer ${val("officePreference", d.officePreference, "set `applyDefaults.officePreference`")}.`,
  `- Salary expectations: ${val("salaryAnswerStyle", d.salaryAnswerStyle, "set `applyDefaults.salaryAnswerStyle`")}`,
  `- Age bracket (optional diversity surveys): ${val("ageBracket", d.ageBracket, "set `applyDefaults.ageBracket`, e.g. \"Under 30\"")}`,
  d.gpa ? `- GPA (required on some forms): **${d.gpa}**` : null,
  `- Essay/free-text answers: ${val("essayStyle", d.essayStyle, "set `applyDefaults.essayStyle`")}`,
  "",
  "## Education",
  "",
  `- Highest level: ${val("highestEducationLevel", profile.highestEducationLevel, "set `highestEducationLevel`")}`,
  educationList
    ? `- Full history: ${educationList}. On multi-entry forms list all of them; on single-entry forms use the highest and flag it so the candidate can override.`
    : "- Full history: **NOT SET — add `education` to the profile**",
  "",
  "## EEO / demographic self-identification",
  "",
  demographics.length > 0
    ? `- ${demographics.join("; ")}. Fill these in when a form offers matching options — optional under EEO law, but no reason to skip once known.`
    : "- **NOT SET on the profile.** These are legally optional: select \"decline to answer\" / \"prefer not to say\" rather than guessing.",
  "",
  ...(d.extraNotes?.length
    ? ["## Other settled answers", "", ...d.extraNotes.map((n) => `- ${n}`), ""]
    : []),
];

if (missing.length > 0) {
  lines.push(
    "## Unset fields",
    "",
    "These have no answer on file. **Pause and ask the candidate** rather than guessing, and consider setting them so the next run doesn't have to ask:",
    "",
    ...missing.map((m) => `- ${m}`),
    ""
  );
}

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.filter((l) => l !== null).join("\n"));

console.log(`Wrote ${path.relative(process.cwd(), OUT)} for ${profile.name}.`);
if (missing.length > 0) {
  console.log(`\n${missing.length} field(s) unset — the skill will ask rather than guess:`);
  for (const m of missing) console.log(`  - ${m}`);
  console.log("\nSet them under `applyDefaults` in local/profile.seed.json, re-seed, and regenerate.");
} else {
  console.log("All standing answers are on file.");
}
process.exit(0);
